<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>calculate acd triff</name>
  <uuid>ea05eb3d-c7e9-460c-b955-d5bc98df2159</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to (decision/100) * the Total value ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
