<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>Total Tariffs</name>
  <uuid>c7cf4a55-51a8-4cba-866e-97fa46cfccad</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[	set decision to 'Get CD' + 'Get ACD' + 'Get ST' + 'Get IT' ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
