<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>get cd value</name>
  <uuid>2be0c00b-2b7c-477c-b55d-fc9e546027e6</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to (decision/100) * the Total value ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
