<?xml version="1.0" encoding="UTF-8"?>
<ilog.rules.studio.model.brl:ActionRule xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:ilog.rules.studio.model.brl="http://ilog.rules.studio/model/brl.ecore">
  <name>calculate tariff</name>
  <uuid>45293bf8-4a55-4e60-a049-447ca4420101</uuid>
  <locale>en_US</locale>
  <definition><![CDATA[set decision to (decision/100) * the Total value ;]]></definition>
</ilog.rules.studio.model.brl:ActionRule>
